name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Altere para a versão do Node que você usa

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Finalizar com sucesso
        if: success()
        run: echo "Testes concluídos com sucesso!"

        on:
  push:
    branches:
      - main

