name: Node.js CI

on:
  push:
    branches:
      - main   # Ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main   # Ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest  # Definindo o sistema operacional para rodar a ação

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Baixa o código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # A versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run tests
        run: npm test  # Roda os testes do projeto

      - name: Upload test results
        if: success()
        run: echo "Testes concluídos com sucesso!"
