name: Node.js CI

on:
  push:
    branches:
      - master  # ou 'main', dependendo da sua branch principal
  pull_request:
    branches:
      - master  # ou 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Define o sistema operacional para rodar a ação

    steps:
      # Passo 1: Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2  # Baixa o código do repositório para o runner

      # Passo 2: Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Define a versão do Node.js que você está usando no projeto

      # Passo 3: Instalação das dependências
      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      # Passo 4: Rodar os testes
      - name: Run tests
        run: npm test  # Roda os testes do projeto (verifique se você tem testes no seu projeto)

      # Passo 5: Mensagem após os testes
      - name: Upload test results
        if: success()
        run: echo "Testes concluídos com sucesso!"
