name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
          cache: 'npm'
          cache-dependency-path: ./src/package-lock.json
      - name: Instalar dependências e Mocha
        run: |
          cd src
          npm install
          npm install -g mocha

      - name: Rodar testes com Mocha
        run: mocha src/conversor.js
        working-directory: ./src

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: davidsantos556/aula-conversao-temperatura:latest

      - name: Mensagem final
        run: echo "✅ CI finalizado com sucesso!"
