name: Node.js CI

on:
  push:
    branches: [ main ]  # Executar quando houver push para a branch 'main'

jobs:
  CI:
    runs-on: ubuntu-latest  # Usando o runner mais atualizado do Ubuntu

    steps:
      - uses: actions/checkout@v2

      # Passo 2: Configuração do Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Versão mais recente do setup-node
        with:
          node-version: 16.13.2

      - name: Instalação do Mocha e dos pacotes para teste
        run: |
          cd src
          npm install -g mocha
          npm install

      

   
